# Generated by Django 2.2.6 on 2019-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('userId', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('GSM', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
