# Generated by Django 2.2.6 on 2019-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='GSM',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='userId',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
