# Generated by Django 2.2.6 on 2019-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='isim', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='isim', max_length=50),
        ),
    ]
