# Generated by Django 2.2.6 on 2020-01-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patientName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
    ]
