# Generated by Django 2.2.6 on 2020-01-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200116_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.District'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Province'),
        ),
    ]
