# Generated by Django 2.2.8 on 2020-01-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200116_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
            ],
        ),
    ]
