# Generated by Django 2.2.6 on 2020-01-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200116_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor'),
        ),
    ]
