# Generated by Django 2.2.6 on 2020-01-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200116_2113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospitals',
            unique_together={('name', 'district')},
        ),
    ]
