# Generated by Django 2.2.6 on 2020-01-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200116_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
    ]
