# Generated by Django 2.2.6 on 2020-01-16 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20200117_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='patient',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
