# Generated by Django 2.2.8 on 2020-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
