# Generated by Django 2.2.6 on 2019-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('PatientName', models.CharField(max_length=40)),
                ('DoctorName', models.CharField(max_length=40)),
            ],
        ),
    ]
