# Generated by Django 2.2.8 on 2019-12-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
