# Generated by Django 2.2.6 on 2020-01-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200116_2130'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('Date', 'Time', 'doctor', 'district', 'province', 'hospital', 'clinic')},
        ),
    ]
