# Generated by Django 2.2.8 on 2019-12-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescript',
        ),
    ]
