# Generated by Django 2.2.6 on 2020-01-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200117_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(),
        ),
    ]
