# Generated by Django 2.2.7 on 2019-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('userId', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gsm', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('workDays', models.DateTimeField(max_length=30)),
                ('workHours', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
